"""dd generated_tests table

Revision ID: 9d1e41b25063
Revises: 
Create Date: 2025-11-14 13:55:23.517250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d1e41b25063'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_tests', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('generated_tests', 'generated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('generated_tests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_tests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('generated_tests', 'generated_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('generated_tests', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
